
project:
  type: website
  output-dir: docs
  resources:
    - images/
    - ANALYSES_FACTORIELLES/
    - FORMATIONS/

website:
  title: "DJAMAL SITE"
  navbar:
    logo: images/logo.png
    logo-href: index.qmd
    left:
      - href: index.qmd
        text: Home
      - text: Analyses Factorielles
        menu: 
          - href: "ANALYSES_FACTORIELLES/TP03.qmd"
            text: Travaux pratiques N02 sur les méthodes d'analyses factorielles
        menu: 
          - href: "FORMATIONS/PAYANTES/R/Formation-en-R.qmd"
            text: Formation en R
      - text: A propos de moi
        href: about.qmd
        

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
