
project:
  type: website
  output-dir: docs
  resources:
    - images/
    - ENGLISH/
    - ENGLISH/images/
    - STATISTIC/

website:
  title: "DJAMAL SITE"
  navbar:
    logo: images/logo.png
    logo-href: index.qmd
    left:
      - href: index.qmd
        text: Home
      - text: Statistic
        menu: 
          - href: "STATISTIC/STAT_DESC/1TP/Exercies.qmd"
            text: Practical work 1
          - href: "STATISTIC/STAT_DESC/tp05/tp05.qmd"
            text: Practical work 5
          
      - text: English
        menu: 
          - href: "ENGLISH/English-Presentations-with-Milonnet.qmd"
            text: English Presentations with Milonnet 18 Nov
      - about.qmd
          
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
