
project:
  type: website
  output-dir: docs
  resources:
    - images/
    - ANALYSES_FACTORIELLES/

website:
  title: "DJAMAL SITE"
  navbar:
    logo: images/logo.png
    logo-href: index.qmd
    left:
      - href: index.qmd
        text: Home
      - text: Analyses Factorielles
        menu: 
          - href: "ANALYSES_FACTORIELLES/TP03.qmd"
            text: Travaux pratiques N02 sur les méthodes d'analyses factorielles
      - about.qmd
          
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
