
project:
  type: website
  output-dir: docs
  resources:
    - images/
    - ANALYSES_FACTORIELLES/
    - FORMATIONS/
    - INFO-MINI-PROJETS/

website:
  title: "DJAMAL SITE"
  navbar:
    logo: images/logo.png
    logo-href: index.qmd
    left:
      - href: index.qmd
        text: Home
      - text: Statistic
        menu: 
          - href: "ANALYSES_FACTORIELLES/TP03.qmd"
            text: Analyse en Composantes Principales et Analyse Factorielle Multiple
      - text: Programming
        menu: 
          - href: "INFO-MINI-PROJETS/assistant-virtuel.qmd"
            text: Crée ton assistant virtuel avec pyhton
      - text: A propos de moi
        href: about.qmd
        

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
