---
title: "Djamaldbz - Expertise en Statistiques"
header-includes:
  - <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
  - <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
  - <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

---

Bienvenue sur le site **Djamaldbz**, dédié à mes travaux en statistiques et informatique. Explorez mes projets, mes recherches, et mes publications.

---

## Qui suis-je ?

Je suis **Djamal Y. TOE**, passionné de statistiques et d'informatique, avec un fort accent sur l'analyse avancée et la résolution de problèmes à travers des méthodes quantitatives.  
Mon objectif est d'apporter des solutions innovantes et pratiques dans le domaine des statistiques et de la science des données.

> **En savoir plus sur moi** [ici](https://djamal2905.github.io/djamaldbz/about.html)

---

## Mon expertise

Je combine mes compétences en statistiques, programmation et analyse de données pour résoudre des problèmes complexes et fournir des solutions pratiques.  
Voici un aperçu de mes domaines d'expertise :

- **Analyses Factorielles et Visualisation**
- **Modèles de Régression et Prévisions**
- **Applications Statistiques Interactives**
- **Développement d'Applications Bureau et Web**
- **Vision par Ordinateur (Computer Vision en apprentissage)**

---

## Mes projets récents

Voici quelques-uns de mes projets récents dans le domaine des statistiques et de l'analyse de données :

- [Analyse Factorielle et Visualisation Avancée](#)
- [Modélisation de Régressions Mixtes pour des données complexes](#)
- [Développement d'outils interactifs pour la visualisation de données](#)

> **Voir tous mes projets** [Bientôt disponible]

---

## Dernières publications

Voici les dernières publications sur des sujets de statistiques et d'informatique que j'ai partagées :

- [Exploration des Techniques d'Analyse Factorielle](#)
- [Guide pratique pour les modèles mixtes](#)
- [Visualisation dynamique avec R et Quarto](#)

> **Voir toutes les publications** [Bientôt disponible]

---

## Contactez-moi

Si vous avez des questions ou souhaitez collaborer sur un projet, n'hésitez pas à me contacter !

> [Envoyer un message](mailto:djamaltoe@example.com)

---


```{=html}
<footer style="background-color: #23242a; color: white; padding: 40px 0;">
  <div class="container">
    <div class="row">
      <div class="col-lg-4">
        <h5 class="text-uppercase">A propos de nous</h5>
        <p>Elève en Science de données à l'Ecole Nationale de la Statistique et de l'Analyse de l'Information en France, titulaire d'une licence en Statistiques-informatique</p>
        <div>
          <a href="#" class="btn btn-floating btn-primary btn-lg"><i class="fab fa-facebook-f"></i></a>
          <a href="#" class="btn btn-floating btn-primary btn-lg"><i class="fab fa-twitter"></i></a>
          <a href="#" class="btn btn-floating btn-primary btn-lg"><i class="fab fa-linkedin"></i></a>
        </div>
      </div>

      <div class="col-lg-4">
        <h6 class="text-uppercase">Rechercher quelque chose ?</h6>
        <input type="text" id="formControlLg" class="form-control" placeholder="Rechercher">
        <ul class="fa-ul">
          <li><i class="fas fa-home"></i> Rennes,35000, France</li>
          <li><i class="fas fa-envelope"></i> djamaltoe2905@gmail.com</li>
          <li><i class="fas fa-phone"></i> +33 ** ** ** ** **</li>
        </ul>
      </div>

      <div class="col-lg-4">
        <h6 class="text-uppercase">Heure de services</h6>
        <table class="table text-white">
          <tr><td>Lundi</td><td>8h30pm - 9:30pm</td></tr>
          <tr><td>Mardi - Vendredi</td><td>7pm - 8pm</td></tr>
          <tr><td>Samedi</td><td>9:30am - 10:30am</td></tr>
        </table>
      </div>
    </div>
  </div>
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2024 Copyright: <a href="https://www.youtube.com/@djamalyoussouftoe" class="text-white">DJAMAL DEV</a>
  </div>
</footer>
```



